#!/bin/bash
set -e

export APP_WORKERS_AMOUNT=${APP_WORKERS_AMOUNT:-2}
export APP_WORKERS_MEMORY_LIMIT=${APP_WORKERS_MEMORY_LIMIT:-256M}
export PHP_OPCACHE_ENABLED=${PHP_OPCACHE_ENABLED:-1}
export PHP_OPCACHE_CLI_ENABLED=${PHP_OPCACHE_CLI_ENABLED:-0}
export PHP_OPCACHE_MEMORY_CONSUMPTION=${PHP_OPCACHE_MEMORY_CONSUMPTION:-128}
export PHP_OPCACHE_MAX_ACCELERATED_FILES=${PHP_OPCACHE_MAX_ACCELERATED_FILES:-20000}
export PHP_OPCACHE_MAX_WASTED_PERCENTAGE=${PHP_OPCACHE_MAX_WASTED_PERCENTAGE:-10}
export PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
export PHP_OPCACHE_JIT_BUFFER_SIZE=${PHP_OPCACHE_JIT_BUFFER_SIZE:-128M}
export PHP_OPCACHE_JIT_MODE=${PHP_OPCACHE_JIT_MODE:-tracing}
export PHP_OPCACHE_REVALIDATE_FREQ=${PHP_OPCACHE_REVALIDATE_FREQ:-0}

envsubst < /usr/local/etc/php/conf.d/opcache.ini.template \
         > /usr/local/etc/php/conf.d/opcache.ini

envsubst < /etc/supervisor/conf.d/laravel-worker.conf.template \
         > /etc/supervisor/conf.d/laravel-worker.conf

exec "$@"
