[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php -d memory_limit=${APP_WORKERS_MEMORY_LIMIT} /var/www/html/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=${APP_WORKERS_AMOUNT}
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600
