server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    # needed for Traefik reverse proxy
    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;

    access_log /var/www/html/storage/logs/nginx_access.log;
    error_log  /var/www/html/storage/logs/nginx_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        include fastcgi_params;
        fastcgi_read_timeout 600;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
